version: '3.3'
services:
  manti-django:
    image: mantiby/mantiby:latest
    ports:
      - "8000:8000"
    links:
      - manti-postgres
      - manti-redis
    volumes:
      - ./:/code
      - ../content:/content
      - ../static:/static
    command: python3 /code/app/manage.py runserver 0.0.0.0:8000 --settings=core.settings.docker
  manti-postgres:
    image: postgres:9.6
    volumes:
      - ./deploy/manti.by.sql:/docker-entrypoint-initdb.d/manti.by.sql
    environment:
      - POSTGRES_DB=manti
      - POSTGRES_USER=manti
      - POSTGRES_PASSWORD=pa55word
  manti-redis:
      image: redis:latest