version: 2
jobs:
  build:
    working_directory: /code
    docker:
      - image: mantiby/manti.by-app:latest
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: manti
          POSTGRES_USER: manti
          POSTGRES_PASSWORD: pa55word
    steps:
      - checkout
      - run:
          name: Install base dependencies
          command: |
            pip3 install -r requirements.app.txt
            pip3 install -r requirements.dev.txt
          working_directory: /code/deploy
      - run:
          name: Run flake8
          command: flake8
          working_directory: /code/app
      - run:
          name: Run migrations
          command: python3 manage.py migrate --settings=core.settings.test
          working_directory: /code/app
      - run:
          name: Run tests
          command: python3 manage.py test --settings=core.settings.test
          working_directory: /code/app