version: '3.3'
services:
  manti-by-postgres:
    image: postgres:9.6
    container_name: manti-by-postgres
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=manti
      - POSTGRES_USER=manti
      - POSTGRES_PASSWORD=pa55word
    logging:
      driver: "none"
  manti-by-redis:
    image: redis:latest
    container_name: manti-by-redis
    logging:
      driver: "none"
  manti-by-memcached:
    image: memcached:latest
    container_name: manti-by-memcached
    logging:
      driver: "none"
  manti-by-app:
    image: mantiby/manti.by:latest
    container_name: manti-by-app
    ports:
      - "8080:8080"
      - "8888:8888"
      - "5555:5555"
    links:
      - manti-by-postgres
      - manti-by-memcached
      - manti-by-redis
    volumes:
      - ../:/srv/manti.by/src/
      - ../../log/:/var/log/manti.by/
      - ../../static/:/srv/manti.by/static/
      - /media/manti/data/Dropbox/Development/Manti.by/content/:/srv/manti.by/content/
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.docker