version: '3.3'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=manti_by
      - POSTGRES_USER=manti_by
      - POSTGRES_PASSWORD=manti_by
    logging:
      driver: "none"

  redis:
    image: redis:latest
    restart: always
    logging:
      driver: "none"

  django:
    image: mantiby/manti.by:latest
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=settings.prod
    volumes:
      - /home/manti/www/manti.by/src/app/:/srv/manti.by/src/
      - /mnt/nostromo/manti.by/log/:/var/log/manti.by/
      - /mnt/nostromo/manti.by/static/:/var/lib/manti.by/static/
      - /mnt/nostromo/manti.by/content/:/var/lib/manti.by/content/
    command: |
      gunicorn wsgi:application -w 2 -b 0.0.0.0:8080 --log-file /var/log/manti.by/wsgi.log

  worker:
    image: mantiby/manti.by:latest
    restart: always
    links:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=settings.prod
    volumes:
      - /home/manti/www/manti.by/src/app/:/srv/manti.by/src/
      - /mnt/nostromo/manti.by/log/:/var/log/manti.by/
      - /mnt/nostromo/manti.by/content/:/var/lib/manti.by/content/
    command: |
      python manage.py rqworker default
