version: '3.3'
services:

  manti-by-postgres:
    image: postgres:latest
    container_name: manti-by-postgres
    restart: always
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=manti
      - POSTGRES_USER=manti
      - POSTGRES_PASSWORD=pa55word
    logging:
      driver: "none"

  manti-by-redis:
    image: redis:latest
    container_name: manti-by-redis
    restart: always
    logging:
      driver: "none"

  manti-by-app:
    image: mantiby/manti.by:latest
    container_name: manti-by-app
    restart: always
    ports:
      - 8080:8080
    links:
      - manti-by-postgres
      - manti-by-redis
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    volumes:
      - /home/manti/www/manti.by/src/:/srv/manti.by/src/
      - /mnt/nostromo/manti.by/log/:/var/log/manti.by/
      - /mnt/nostromo/manti.by/static/:/var/lib/manti.by/static/
      - /mnt/nostromo/manti.by/content/:/var/lib/manti.by/content/
    command: |
      gunicorn core.wsgi:application -w 2 -b 0.0.0.0:8080 --log-file /var/log/manti.by/wsgi.log

  manti-by-celery:
    image: mantiby/manti.by:latest
    container_name: manti-by-celery
    restart: always
    links:
      - manti-by-postgres
      - manti-by-redis
    volumes:
      - /home/manti/www/manti.by/src/:/srv/manti.by/src/
      - /mnt/nostromo/manti.by/log/:/var/log/manti.by/
      - /mnt/nostromo/manti.by/content/:/var/lib/manti.by/content/
    command: |
      python manage.py rqworker default
