version: '3.3'
services:

  manti-by-postgres:
    image: postgres:latest
    container_name: manti-by-postgres
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=manti
      - POSTGRES_USER=manti
      - POSTGRES_PASSWORD=pa55word
    logging:
      driver: "none"

  manti-by-redis:
    image: redis:latest
    container_name: manti-by-redis
    logging:
      driver: "none"

  manti-by-memcache:
    image: memcached:latest
    container_name: manti-by-memcache
    logging:
      driver: "none"

  manti-by-app:
    image: mantiby/manti.by:latest
    container_name: manti-by-app
    ports:
      - 8080:8080
    links:
      - manti-by-postgres
      - manti-by-memcache
      - manti-by-redis
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - ROLE=app
    volumes:
      - /home/manti/www/manti.by/src/:/srv/manti.by/src/
      - /mnt/nostromo/manti.by/log/:/var/log/manti.by/
      - /mnt/nostromo/manti.by/static/:/var/lib/manti.by/static/
      - /mnt/nostromo/manti.by/content/:/var/lib/manti.by/content/

  manti-by-celery:
    image: mantiby/manti.by:latest
    container_name: manti-by-celery
    links:
      - manti-by-postgres
      - manti-by-redis
    volumes:
      - /home/manti/www/manti.by/src/:/srv/manti.by/src/
      - /mnt/nostromo/manti.by/log/:/var/log/manti.by/
      - /mnt/nostromo/manti.by/content/:/var/lib/manti.by/content/
    environment:
      - ROLE=celery

  manti-by-flower:
    image: mantiby/manti.by:latest
    container_name: manti-by-flower
    ports:
      - 5555:5555
    links:
      - manti-by-postgres
      - manti-by-redis
    volumes:
      - /home/manti/www/manti.by/src/:/srv/manti.by/src/
      - /mnt/nostromo/manti.by/log/:/var/log/manti.by/
    environment:
      - ROLE=flower
