name: Backend

on:
  push:
    branches:
      - master
      - develop

jobs:
  checks:

    name: Run Django checks

    runs-on: ubuntu-latest

    container:

      image: mantiby/manti.by:latest

    services:

      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: manti_by
          POSTGRES_PASSWORD: manti_by
          POSTGRES_DB: manti_by
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('deploy/requirements/dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/requirements/dev.txt

      - name: Check for missing migrations
        run: |
          python app/manage.py makemigrations --dry-run --check --verbosity=3 --settings=core.settings.test

      - name: Run Django system checks
        run: |
          python app/manage.py check --fail-level WARNING --settings=core.settings.test

  tests:

    name: Run test suite

    needs: checks

    runs-on: ubuntu-latest

    container:

      image: mantiby/manti.by:latest

    services:

      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: manti_by
          POSTGRES_PASSWORD: manti_by
          POSTGRES_DB: manti_by
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('deploy/requirements/dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/requirements/dev.txt

      - name: Run Pytest suite
        run: |
          pytest --create-db --disable-warnings app/
